### ISSUE TITLE
Compile error in Mac osX

### ISSUE THREAD

**Issue by jeyhan** [mkfs/opdis#19]
/usr/include/stdlib.h:151:18: note: passing argument to parameter here
void     free(void *);
                    ^
opdis/opdis.c:265:26: error: use of undeclared identifier
      'print_insn_i386_intel'
        disassembler_ftype fn = print_insn_i386_intel;
                                ^
opdis/opdis.c:273:8: error: use of undeclared identifier 'print_insn_i386_att'
                fn = print_insn_i386_att;
                     ^
1 warning and 3 errors generated.
make: *** [opdis/opdis.lo] Error 1

**Comment by mkfs** [comment]
hmm - is GNU libopcodes present on OS X? I thought they had their own library for that.

Make sure GNU binutils is installed, including all static libraries and header files.

**Comment by mkfs** [comment]
looks like a standard drive-by complaint

**Comment by oxavelar** [comment]
To me I think this error happens when trying to compile with GCC 8.2+

If I compile with GCC 6.x the warning is not present.... mmm

It looks like:

`gcc/8.2.0/include/dis-asm.h`

Doesn't have print_insn_i386_intel defined anymore here, look @ 

[6394c606997f88acfc80de4dff33a4ae2de987b4](https://github.com/redox-os/binutils-gdb/commit/6394c606997f88acfc80de4dff33a4ae2de987b4#diff-ffcda348b044d6f5c6ef12726ee3fbb9)

Looks like on top of 

`#include "dis-asm.h"`

We will now only need:

`#include "disassemble.h"`

Do you also see this?
